# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12ac8d55749add54117f5dc63ff8268f6468cebcfb640ca905efa3a9ba04d65fd2c48c0d1a1591cbb98346bef0bcde6f20fa3e244211c29d37db44f22e98f62e

test:
  secret_key_base: 5df2315fdc1f26e97f8b62880a24bc9f8776923a6ce33f998f46d0b55e393364a3695eec57bbc9e99f9ce401f3b5a9826be01deffdaf858cb4c84696261606bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
